"""Record the installed Python 3.11 runtime dependency closure (Windows + Linux)."""
from importlib.metadata import distribution
from pathlib import Path
from packaging.markers import default_environment
from packaging.requirements import Requirement

ROOT = Path(__file__).resolve().parents[1]
roots = ['qq-botpy', 'python-dotenv', 'requests', 'openai', 'python-docx', 'openpyxl',
         'fastapi', 'httpx', 'uvicorn', 'tzdata', 'Pillow', 'PyYAML', 'packaging']
environments = [dict(default_environment(), sys_platform=platform, platform_system=system, os_name=os_name, extra='')
    for platform, system, os_name in [('win32', 'Windows', 'nt'), ('linux', 'Linux', 'posix')]]
pending, versions = list(roots), {}
while pending:
    name = pending.pop().lower().replace('_', '-')
    if name in versions:
        continue
    package = distribution(name)
    versions[name] = package.version
    for raw in package.requires or []:
        requirement = Requirement(raw)
        if requirement.marker is None or any(requirement.marker.evaluate(env) for env in environments):
            pending.append(requirement.name)
target = ROOT / 'constraints-py311.txt'
target.write_text('# Installed dependency closure, Python 3.11; generated by scripts/lock_dependencies.py\n'
    '# Version constraints, not artifact hashes. Install requirements with -c this file.\n'
    + ''.join(f'{name}=={version}\n' for name, version in sorted(versions.items())), encoding='utf-8')
print(f'{len(versions)} pinned distributions -> {target}')
